# Generated by Django 5.1.1 on 2024-09-28 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrebudApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img_ava', models.ImageField(upload_to='avatars/')),
            ],
            options={
                'db_table': 'seller',
            },
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GrebudApp.seller'),
        ),
    ]
